install:	ospac
	cp ospac /usr/local/bin
	cp ../ospac.1 /usr/local/share/man/man1/

install-gui:	ospac-gui
	cp ospac-gui /usr/local/bin
	cp ../ospac.1 /usr/local/share/man/man1/

uninstall:
	rm -f /usr/local/bin/ospac
	rm -f /usr/local/bin/ospac-gui
	rm -f /usr/local/share/man/man1/ospac.1

